# Generated by Django 3.2.13 on 2022-10-06 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='summarty',
            new_name='summary',
        ),
    ]
